CREATE TABLE DEPT (
    DEPARTMENTID INT PRIMARY KEY,
    DEPARTMENTNAME VARCHAR(100) NOT NULL UNIQUE,
    DEPARTMENTCODE VARCHAR(50) NOT NULL UNIQUE,
    LOCATION VARCHAR(50) NOT NULL
);

CREATE TABLE PERSON (
    PERSONID INT PRIMARY KEY,
    PERSONNAME VARCHAR(100) NOT NULL,
    DEPARTMENTID INT NULL,
    SALARY DECIMAL(8, 2) NOT NULL,
    JOININGDATE DATETIME NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    FOREIGN KEY (DEPARTMENTID) REFERENCES DEPT(DEPARTMENTID)
);

INSERT INTO DEPT (DEPARTMENTID, DEPARTMENTNAME, DEPARTMENTCODE, LOCATION) VALUES
(1, 'ADMIN', 'ADM', 'A-BLOCK'),
(2, 'COMPUTER', 'CE', 'C-BLOCK'),
(3, 'CIVIL', 'CI', 'G-BLOCK'),
(4, 'ELECTRICAL', 'EE', 'E-BLOCK'),
(5, 'MECHANICAL', 'ME', 'B-BLOCK');

INSERT INTO PERSON (PERSONID, PERSONNAME, DEPARTMENTID, SALARY, JOININGDATE, CITY) VALUES
(101, 'RAHUL TRIPATHI', 2, 56000, '2000-01-01', 'RAJKOT'),
(102, 'HARDIK PANDYA', 3, 18000, '2001-09-25', 'AHMEDABAD'),
(103, 'BHAVIN KANANI', 4, 25000, '2000-05-14', 'BARODA'),
(104, 'BHOOMI VAISHNAV', 1, 39000, '2005-02-08', 'RAJKOT'),
(105, 'ROHIT TOPIYA', 2, 17000, '2001-07-23', 'JAMNAGAR'),
(106, 'PRIYA MENPARA', NULL, 9000, '2000-10-18', 'AHMEDABAD'),
(107, 'NEHA SHARMA', 2, 34000, '2002-12-25', 'RAJKOT'),
(108, 'NAYAN GOSWAMI', 3, 25000, '2001-07-01', 'RAJKOT'),
(109, 'MEHUL BHUNDIYA', 4, 13500, '2005-01-09', 'BARODA'),
(110, 'MOHIT MARU', 5, 14000, '2000-05-25', 'JAMNAGAR');


----------------PART-A----------------
--1. Find all persons with their department name & code.
SELECT P.PERSONNAME,D.DEPARTMENTNAME,D.DEPARTMENTID FROM PERSON AS P
LEFT JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID

--2. Find the person's name whose department is in C-Block.
SELECT P.PERSONNAME FROM PERSON AS P
JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE D.LOCATION = 'C-BLOCK'

--3. Retrieve person name, salary & department name who belongs to Jamnagar city.
SELECT P.PERSONNAME,P.SALARY,D.DEPARTMENTNAME FROM PERSON AS P
JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID

--4. Retrieve person name, salary & department name who does not belong to Rajkot city.
SELECT P.PERSONNAME,P.SALARY,D.DEPARTMENTNAME FROM PERSON AS P
JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE P.CITY <> 'RAJKOT'

--5. Retrieve person’s name of the person who joined the Civil department after 1-Aug-2001.
SELECT P.PERSONNAME,P.JOININGDATE FROM PERSON AS P
JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE P.JOININGDATE > '2001-8-1' AND D.DEPARTMENTNAME = 'CIVIL'

--6. Find details of all persons who belong to the computer department.
SELECT P.PERSONNAME,D.DEPARTMENTNAME FROM PERSON AS P
JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTNAME ='COMPUTER'

--7. Display all the person's name with the department whose joining date difference with the current date 
--is more than 365 days.
SELECT P.PERSONNAME,D.DEPARTMENTNAME FROM PERSON AS P
JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE DATEDIFF(DAY,P.JOININGDATE,GETDATE()) > 365

--8. Find department wise person counts.
SELECT D.DEPARTMENTNAME,COUNT(P.PERSONID) FROM PERSON AS P
JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME

--9. Give department wise maximum & minimum salary with department name.
SELECT D.DEPARTMENTNAME,MAX(P.SALARY),MIN(P.SALARY),D.DEPARTMENTNAME FROM PERSON AS P
JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME

--10. Find city wise total, average, maximum and minimum salary.
SELECT P.CITY,SUM(P.SALARY),AVG(P.SALARY),MAX(P.SALARY),MIN(P.SALARY) FROM PERSON AS P
JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY P.CITY

--11. Find the average salary of a person who belongs to Ahmedabad city.
SELECT P.CITY,AVG(P.SALARY) FROM PERSON AS P
GROUP BY P.CITY
HAVING P.CITY = 'AHMEDABAD'

--12. Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In 
--single colum
SELECT P.PERSONNAME+'LIVES IN'+P.CITY+'AND WORKS IN'+D.DEPARTMENTNAME FROM PERSON AS P
LEFT JOIN DEPT D
ON P.DEPARTMENTID=D.DEPARTMENTID

-----------PART-B----------

--1. Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly. (In 
--single column)
SELECT P.PERSONNAME+' EARNS '+STR(P.SALARY)+' FROM ' + D.DEPARTMENTNAME+' DEPARTMENT MONTHLY ' FROM PERSON P
LEFT JOIN DEPT D
ON P.DEPARTMENTID = D.DEPARTMENTID 

--2. Find city & department wise total, average & maximum salaries.
SELECT P.CITY,D.DEPARTMENTNAME,SUM(P.SALARY),AVG(P.SALARY),MAX(P.SALARY) FROM PERSON AS P
JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY P.CITY,D.DEPARTMENTNAME

--3. Find all persons who do not belong to any department.
SELECT P.PERSONNAME FROM PERSON P
LEFT JOIN DEPT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTID IS NULL

--4. Find all departments whose total salary is exceeding 100000.
SELECT D.DEPARTMENTNAME,SUM(P.SALARY) FROM PERSON AS P
JOIN DEPT AS D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING SUM(P.SALARY) > 10000

--------------PART-C----------------
--1. List all departments who have no person.
SELECT D.DEPARTMENTNAME FROM PERSON P
JOIN DEPT D
ON P.DEPARTMENTID= D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING COUNT(P.PERSONID)=0

--2. List out department names in which more than two persons are working.
SELECT D.DEPARTMENTNAME FROM PERSON P
JOIN DEPT D
ON P.DEPARTMENTID= D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING COUNT(P.PERSONID) >2

--3. Give a 10% increment in the computer department employee’s salary. (Use Update)
UPDATE  PERSON
SET PERSON.SALARY = PERSON.SALARY + (SALARY)*0.1
FROM PERSON
JOIN DEPT
ON PERSON.DEPARTMENTID = DEPT.DEPARTMENTID
WHERE DEPT.DEPARTMENTNAME = 'COMPUTER'

UPDATE  PERSON
SET SALARY = SALARY + (SALARY)*0.1
WHERE DEPARTMENTID IN(SELECT DEPARTMENTID FROM DEPT WHERE DEPARTMENTNAME='COMPUTER')




